# Generated by Django 3.1.5 on 2021-01-27 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=100)),
                ('imdb_url', models.CharField(max_length=100)),
                ('decade', models.CharField(max_length=1000)),
                ('genres', models.CharField(max_length=1000)),
                ('avg_rating', models.FloatField(default=5)),
                ('poster', models.CharField(max_length=1000)),
                ('cast', models.CharField(default='No cast found.', max_length=10000)),
                ('director', models.CharField(default='No director found.', max_length=100)),
                ('description', models.CharField(default='No description found.', max_length=10000)),
                ('keyword', models.CharField(default='No keyword found.', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('stars', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
